//! Sandboxed file system operations for agent tool execution.

use std::io;
use std::path::{Path, PathBuf};

/// File system operations scoped to a workspace root.
/// All paths are validated to prevent directory traversal.
pub struct SandboxedFs {
    root: PathBuf,
}

impl SandboxedFs {
    pub fn new(root: PathBuf) -> Self {
        Self { root }
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Resolve a relative path within the sandbox. Returns an error if the
    /// resolved path escapes the root.
    fn resolve(&self, relative: &str) -> io::Result<PathBuf> {
        // Normalize the root first (resolve symlinks on macOS /tmp -> /private/tmp)
        let canonical_root = self.root.canonicalize().unwrap_or_else(|_| self.root.clone());

        // Normalize path components to catch traversal attempts
        let mut components = Vec::new();
        for component in Path::new(relative).components() {
            match component {
                std::path::Component::ParentDir => {
                    if components.is_empty() {
                        return Err(io::Error::new(
                            io::ErrorKind::PermissionDenied,
                            "Path escapes sandbox root",
                        ));
                    }
                    components.pop();
                }
                std::path::Component::Normal(c) => components.push(c.to_os_string()),
                std::path::Component::CurDir => {}
                _ => {
                    return Err(io::Error::new(
                        io::ErrorKind::PermissionDenied,
                        "Absolute paths not allowed in sandbox",
                    ));
                }
            }
        }

        let mut resolved = canonical_root;
        for c in components {
            resolved.push(c);
        }
        Ok(resolved)
    }

    pub fn read_file(&self, relative: &str) -> io::Result<String> {
        let path = self.resolve(relative)?;
        std::fs::read_to_string(path)
    }

    pub fn write_file(&self, relative: &str, content: &str) -> io::Result<()> {
        let path = self.resolve(relative)?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, content)
    }

    pub fn create_dir(&self, relative: &str) -> io::Result<()> {
        let path = self.resolve(relative)?;
        std::fs::create_dir_all(path)
    }

    pub fn list_dir(&self, relative: &str) -> io::Result<Vec<String>> {
        let path = self.resolve(relative)?;
        let mut entries = Vec::new();
        for entry in std::fs::read_dir(path)? {
            let entry = entry?;
            entries.push(entry.file_name().to_string_lossy().to_string());
        }
        Ok(entries)
    }

    /// Scaffold a new project with standard structure.
    /// Creates README, CHANGELOG, specs/ directory, and optional files.
    pub fn scaffold_project(&self, title: &str, spec: &str) -> io::Result<()> {
        // Ensure root exists
        std::fs::create_dir_all(&self.root)?;

        // README.md
        let readme = format!(
            "# {title}\n\n> Auto-generated by Beaver Builder\n\n## Overview\n\n{spec}\n"
        );
        self.write_file("README.md", &readme)?;

        // CHANGELOG.md
        let changelog = format!(
            "# Changelog\n\n## [Unreleased]\n\n- Initial scaffold for: {title}\n"
        );
        self.write_file("CHANGELOG.md", &changelog)?;

        // specs/ directory with the spec file
        self.create_dir("specs")?;
        self.write_file("specs/initial-spec.md", &format!("# Specification\n\n{spec}\n"))?;

        // .gitignore
        self.write_file(
            ".gitignore",
            "# OS\n.DS_Store\nThumbs.db\n\n# IDE\n.idea/\n.vscode/\n*.swp\n\n# Build\ntarget/\ndist/\nnode_modules/\n",
        )?;

        Ok(())
    }

    /// Check if specific files exist in the sandbox.
    pub fn files_exist(&self, paths: &[&str]) -> bool {
        paths.iter().all(|p| {
            self.resolve(p)
                .map(|path| path.exists())
                .unwrap_or(false)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn scaffold_creates_expected_files() {
        let tmp = std::env::temp_dir().join("beaver_test_scaffold");
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).unwrap();

        let sandbox = SandboxedFs::new(tmp.clone());
        sandbox
            .scaffold_project("Test Project", "A test specification")
            .unwrap();

        assert!(tmp.join("README.md").exists());
        assert!(tmp.join("CHANGELOG.md").exists());
        assert!(tmp.join("specs/initial-spec.md").exists());
        assert!(tmp.join(".gitignore").exists());

        let readme = fs::read_to_string(tmp.join("README.md")).unwrap();
        assert!(readme.contains("Test Project"));

        let _ = fs::remove_dir_all(&tmp);
    }

    #[test]
    fn path_traversal_is_blocked() {
        let tmp = std::env::temp_dir().join("beaver_test_traversal");
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).unwrap();

        let sandbox = SandboxedFs::new(tmp.clone());
        let result = sandbox.write_file("../../etc/passwd", "pwned");
        assert!(result.is_err());

        let _ = fs::remove_dir_all(&tmp);
    }
}
